import { Injectable } from '@angular/core';
import {Product} from '../../tools/Product';

@Injectable()
export class ProductService {

  constructor() { }
  getProduct(): Product[] {
    return [
      {
        'productID': 1,
        'productName': 'PC HP',
        'productCode': 'ax004nf',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-hp-omen-15-ax004nf-i7-6e-gen-24-go',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-acer-aspire-v-nitro-vn7-592g-i5-6e-gen-12-go.jpg',
        'prodUrl': '',
      },
      {
        'productID': 2,
        'productName': 'PC acer',
        'productCode': 'sf314',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.052,
        'description': 'pc-portable-acer-swift-3-sf314-i3-4-go',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-acer-swift-3-sf314-i3-4-go.jpg',
        'prodUrl': '',
      },
      {
        'productID': 3,
        'productName': 'PC HP',
        'productCode': 'ay025nk',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-hp-15-ay025nk-dual-core-4-go-noir',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-hp-15-ay025nk-dual-core-4-go-noir.jpg',
        'prodUrl': '',
      },
      {
        'productID': 4,
        'productName': 'PC asus',
        'productCode': 'x541uj',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-asus-vivobook-max-x541uj-i3-6e-gen-8-go',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-asus-vivobook-max-x541uj-i3-6e-gen-8-go.jpg',
        'prodUrl': '',
      },
      {
        'productID': 5,
        'productName': 'iphone-8',
        'productCode': 'ay025nk',
        'productType': 'smartphone',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'iphone-8-gold-silver-et-noir-tunisie',
        'starRating': 4,
        'imageUrl': '../../../assets/images/smartphone/iphone-8-gold-silver-et-noir-tunisie.jpg',
        'prodUrl': '',
      },
      {
        'productID': 3,
        'productName': 'PC HP',
        'productCode': 'ay025nk',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-hp-15-ay025nk-dual-core-4-go-noir',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-hp-15-ay025nk-dual-core-4-go-noir.jpg',
        'prodUrl': '',
      },
      {
        'productID': 3,
        'productName': 'PC HP',
        'productCode': 'ay025nk',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-hp-15-ay025nk-dual-core-4-go-noir',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-hp-15-ay025nk-dual-core-4-go-noir.jpg',
        'prodUrl': '',
      },
      {
        'productID': 3,
        'productName': 'PC HP',
        'productCode': 'ay025nk',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-hp-15-ay025nk-dual-core-4-go-noir',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-hp-15-ay025nk-dual-core-4-go-noir.jpg',
        'prodUrl': '',
      },
      {
        'productID': 3,
        'productName': 'PC HP',
        'productCode': 'ay025nk',
        'productType': 'laptop',
        'releaseDate': '15/02/2017',
        'price': 1.652,
        'description': 'pc-portable-hp-15-ay025nk-dual-core-4-go-noir',
        'starRating': 4,
        'imageUrl': '../../../assets/images/laptop/pc-portable-hp-15-ay025nk-dual-core-4-go-noir.jpg',
        'prodUrl': '',
      }        ];
  }

}
